### ISSUE TITLE
AudFlow Issue

### ISSUE THREAD

**Issue by Dgram19** [asmpro7/AudFlow#1]
Flow Launcher version: 1.14.1
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\User\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 05/13/2023 21:50:42
Exception:
AudFlow Exception: 
Websites: https://github.com/asmpro7/AudFlow
Author: Ahmed ElSaeed
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\AudFlow-1.0.0\main.py", line 14, in <module>
    import pygame
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\AudFlow-1.0.0\lib\pygame\__init__.py", line 92, in <module>
    from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ModuleNotFoundError: No module named 'pygame.base'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\AudFlow-1.0.0\main.py", line 14, in <module>
    import pygame
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\AudFlow-1.0.0\lib\pygame\__init__.py", line 92, in <module>
    from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ModuleNotFoundError: No module named 'pygame.base'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 829
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by asmpro7** [comment]
one your terminal and type this: 
pip install pygame
and tell me the result

**Comment by asmpro7** [comment]
after update the plugin to v2.0.0 you wouldn't face any problem 😊

**Comment by Dgram19** [comment]
I will try and let you know as soon as possible. And thank you for your work 🔥

**Comment by asmpro7** [comment]
thx😁💖
I sent it to the flow launcher team it will be updated soon, let me know after using it ✨

**Comment by Dgram19** [comment]
Ok great 😉

**Comment by Dgram19** [comment]
The update has arrived, however there are problems during installation. It says the latest version is already installed, even though v1.0.0 is installed.

**Comment by asmpro7** [comment]
yes, I make v2.0.1 now, because that problem and send to flow team, soon it will be updated check the version of the plugin in plugin store 😉

**Comment by Dgram19** [comment]
Same issue

Flow Launcher version: 1.14.1
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\user\AppData\Local\Programs\Python\Python311\pythonw.exe
Node Path: 
Date: 05/16/2023 14:11:17
Exception:
AudFlow Exception: 
Websites: https://github.com/asmpro7/AudFlow
Author: Ahmed ElSaeed
Version: 2.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.1\main.py", line 11, in <module>
    from gtts import gTTS
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.1\lib\gtts\init.py", line 3, in <module>
    from .tts import gTTS, gTTSError
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.1\lib\gtts\tts.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.1\main.py", line 11, in <module>
    from gtts import gTTS
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.1\lib\gtts\init.py", line 3, in <module>
    from .tts import gTTS, gTTSError
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.1\lib\gtts\tts.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>cDisplayClass22_0.<<QueryForPluginAsync>b0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>cDisplayClass135_0.<<QueryResults>gQueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by asmpro7** [comment]
sorry for that, it solved in v2.0.2 
you can uninstall AudFlow and download it manually because didnt wait in to add to plugin it take at least one day
from here 
https://github.com/asmpro7/AudFlow/releases/download/v2.0.2/AudFlow.zip
and unzip it here 
C:\Users\<Your username>\AppData\Local\FlowLauncher\app-1.14.1\UserData\Plugins

**Comment by Dgram19** [comment]
Hey sorry, can we talk in private?

**Comment by asmpro7** [comment]
you can, using telegram here: 
t.me/asmprotk

**Comment by asmpro7** [comment]
I using python 3.8 as flow and test it on my device and solve the problems it appear, so It should now work great in
v2.0.3, try it and tell me to close this issue 🤗
