### ISSUE TITLE
Requests package missing

### ISSUE THREAD

**Issue by deefrawley** [asmpro7/AudFlow#3]
Looks like gTTS isn't pulling in dependencies. Happens every time I type the keyword.

```Flow Launcher version: 1.15.0
OS Version: 19045.2965
IntPtr Length: 8
x64: True

Python Path: C:\Users\Damien\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 05/16/2023 08:43:55
Exception:
AudFlow Exception: 
Websites: https://github.com/asmpro7/AudFlow
Author: Ahmed ElSaeed
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.0\main.py", line 11, in <module>
    from gtts import gTTS
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.0\lib\gtts\__init__.py", line 3, in <module>
    from .tts import gTTS, gTTSError
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.0\lib\gtts\tts.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.0\main.py", line 11, in <module>
    from gtts import gTTS
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.0\lib\gtts\__init__.py", line 3, in <module>
    from .tts import gTTS, gTTSError
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.0.0\lib\gtts\tts.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 836
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 837
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by asmpro7** [comment]
wait until the v2.0.1 released in the plugin store, and tell me if the problem appears again.

**Comment by deefrawley** [comment]
Updated, and uninstalled/reinstalled and yes the error still appears.

**Comment by deefrawley** [comment]
I just did a test locally installing your requirements,txt in a virtual env and here are the packages that your plugin should ship with:

![image](https://github.com/asmpro7/AudFlow/assets/18594055/9c5042f9-f4b5-4ec7-bd93-abcb20bee1f0)

**Comment by asmpro7** [comment]
thx!!! 
I now put my hand on problem all thing will be solved in 2.0.2

**Comment by asmpro7** [comment]
Try and tell me, It should work (if there aren't problems in the last one which it didn't take its turn from problems 😂)

**Comment by asmpro7** [comment]
I using python 3.8 as flow and test it on my device and solve the problems it appear , so It should now work great in 
v2.0.3, try it and tell me to close this issue 🤗
