### ISSUE TITLE
flow launcher AU wont work

### ISSUE THREAD

**Issue by Princess7777** [asmpro7/AudFlow#5]
[2024-02-09.txt](https://github.com/asmpro7/AudFlow/files/14219353/2024-02-09.txt)
****
Flow Launcher version: 1.17.1
OS Version: 22631.3085
IntPtr Length: 8
x64: True

Python Path: C:\Users\khash\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 02/09/2024 11:54:03
Exception:
AudFlow Exception: 
Websites: https://github.com/asmpro7/AudFlow
Author: Ahmed ElSaeed
Version: 2.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\khash\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.1.0\main.py", line 105, in <module>
    AudFlow()
  File "C:\Users\khash\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.1.0\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khash\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.1.0\main.py", line 24, in query
    key=settings["execute_key"]
        ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'execute_key'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\khash\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.1.0\main.py", line 105, in <module>
    AudFlow()
  File "C:\Users\khash\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.1.0\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khash\AppData\Roaming\FlowLauncher\Plugins\AudFlow-2.1.0\main.py", line 24, in query
    key=settings["execute_key"]
        ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'execute_key'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by asmpro7** [comment]
do you use execute key in plugin settings?
![image](https://github.com/asmpro7/AudFlow/assets/114514662/0ac4c253-5089-4552-b7f6-3d36c8e9978d)

**Comment by asmpro7** [comment]
Try new release
